{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rhub
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rhub_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rhub/rhub_{{ version }}.tar.gz
  sha256: 87683c0bdb90226e6460d286361aabf86f1d198427347196d60950c1ce960117

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-callr
    - r-cli
    - r-curl
    - r-desc
    - r-gert
    - r-gitcreds
    - r-glue
    - r-jsonlite
    - r-pkgbuild
    - r-processx
    - r-rappdirs
    - r-rematch
    - r-rprojroot
    - r-whoami
  run:
    - r-base
    - r-r6
    - r-callr
    - r-cli
    - r-curl
    - r-desc
    - r-gert
    - r-gitcreds
    - r-glue
    - r-jsonlite
    - r-pkgbuild
    - r-processx
    - r-rappdirs
    - r-rematch
    - r-rprojroot
    - r-whoami

test:
  commands:
    - $R -e "library('rhub')"           # [not win]
    - "\"%R%\" -e \"library('rhub')\""  # [win]

about:
  home: https://github.com/r-hub/rhub, https://r-hub.github.io/rhub/
  license: MIT
  summary: R-hub v2 uses GitHub Actions to run 'R CMD check' and similar package checks. The 'rhub' package helps you set up R-hub v2 for your R package, and start running checks.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
